services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      BROKER_URL: ws://broker:8765
    volumes:
      - .:/app
    depends_on:
      - postgres

  broker:
    build: .
    command: ["python", "-m", "app.broker.broker"]
    ports:
      - "8765:8765"
      - "8001:8001"
    volumes:
      - .:/app
    depends_on:
      - postgres

  prometheus:
    image: prom/prometheus:v2.55.1
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    depends_on:
      - api
      - broker

  grafana:
    image: grafana/grafana-oss:11.5.1
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
      - ./grafana/dashboards:/var/lib/grafana/dashboards:ro
    depends_on:
      - prometheus

  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: admission_platform
    ports:
      - "5432:5432"
