services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - postgres

  broker:
    build: .
    command: ["python", "-m", "app.broker"]
    ports:
      - "8765:8765"
    volumes:
      - .:/app
    depends_on:
      - postgres

  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: admission_platform
    ports:
      - "5432:5432"
